Revert "Gallery2: fix crash when edit a photo"
This fixes the following error for arm64

fatal error: error in backend: Cannot select: 0x5bb2e48: v4f32 = fminnum 0x5bb1d30, 0x5bfa718
  0x5bb1d30: v4f32 = fmaxnum 0x5b0a0f0, 0x5b3a3d8
    0x5b0a0f0: v4f32 = ARMISD::BUILD_VECTOR 0x5b06b98, 0x5b06c68, 0x5b06d38, 0x5b06e08
      0x5b06b98: f32 = fsqrt 0x5b06b30
        0x5b06b30: f32 = extract_vector_elt 0x5bb1b90, Constant:i32<0>
          0x5bb1b90: v4f32 = fadd 0x5bb1ac0, 0x5b620e8
            0x5bb1ac0: v4f32 = fmul 0x5b34bf0, 0x5b34bf0
              0x5b34bf0: v4f32 = bitcast 0x5b34b88
                0x5b34b88: v4i32 = or 0x5b34918, 0x5b34980
                  0x5b34918: v4i32 = and 0x5b33320, 0x5b323e0

                  0x5b34980: v4i32 = and 0x5b31af0, 0x5b33388

              0x5b34bf0: v4f32 = bitcast 0x5b34b88
                0x5b34b88: v4i32 = or 0x5b34918, 0x5b34980
                  0x5b34918: v4i32 = and 0x5b33320, 0x5b323e0

                  0x5b34980: v4i32 = and 0x5b31af0, 0x5b33388

            0x5b620e8: v4f32 = fmul 0x5b324e8, 0x5b324e8
              0x5b324e8: v4f32 = bitcast 0x5b32480
                0x5b32480: v4i32 = or 0x5b45a88, 0x5b45af0
                  0x5b45a88: v4i32 = and 0x5b459b8, 0x5b32240

                  0x5b45af0: v4i32 = and 0x5b2f728, 0x5b45a20

              0x5b324e8: v4f32 = bitcast 0x5b32480
                0x5b32480: v4i32 = or 0x5b45a88, 0x5b45af0
                  0x5b45a88: v4i32 = and 0x5b459b8, 0x5b32240

                  0x5b45af0: v4i32 = and 0x5b2f728, 0x5b45a20

          0x5add898: i32 = Constant<0>
      0x5b06c68: f32 = fsqrt 0x5b06c00
        0x5b06c00: f32 = extract_vector_elt 0x5bb1b90, Constant:i32<1>
          0x5bb1b90: v4f32 = fadd 0x5bb1ac0, 0x5b620e8
            0x5bb1ac0: v4f32 = fmul 0x5b34bf0, 0x5b34bf0
              0x5b34bf0: v4f32 = bitcast 0x5b34b88
                0x5b34b88: v4i32 = or 0x5b34918, 0x5b34980
                  0x5b34918: v4i32 = and 0x5b33320, 0x5b323e0

                  0x5b34980: v4i32 = and 0x5b31af0, 0x5b33388

              0x5b34bf0: v4f32 = bitcast 0x5b34b88
                0x5b34b88: v4i32 = or 0x5b34918, 0x5b34980
                  0x5b34918: v4i32 = and 0x5b33320, 0x5b323e0

                  0x5b34980: v4i32 = and 0x5b31af0, 0x5b33388

            0x5b620e8: v4f32 = fmul 0x5b324e8, 0x5b324e8
              0x5b324e8: v4f32 = bitcast 0x5b32480
                0x5b32480: v4i32 = or 0x5b45a88, 0x5b45af0
                  0x5b45a88: v4i32 = and 0x5b459b8, 0x5b32240

                  0x5b45af0: v4i32 = and 0x5b2f728, 0x5b45a20

              0x5b324e8: v4f32 = bitcast 0x5b32480
                0x5b32480: v4i32 = or 0x5b45a88, 0x5b45af0
                  0x5b45a88: v4i32 = and 0x5b459b8, 0x5b32240

                  0x5b45af0: v4i32 = and 0x5b2f728, 0x5b45a20

          0x5af0088: i32 = Constant<1>
      0x5b06d38: f32 = fsqrt 0x5b06cd0
        0x5b06cd0: f32 = extract_vector_elt 0x5bb1b90, Constant:i32<2>
          0x5bb1b90: v4f32 = fadd 0x5bb1ac0, 0x5b620e8
            0x5bb1ac0: v4f32 = fmul 0x5b34bf0, 0x5b34bf0
              0x5b34bf0: v4f32 = bitcast 0x5b34b88
                0x5b34b88: v4i32 = or 0x5b34918, 0x5b34980
                  0x5b34918: v4i32 = and 0x5b33320, 0x5b323e0

                  0x5b34980: v4i32 = and 0x5b31af0, 0x5b33388

              0x5b34bf0: v4f32 = bitcast 0x5b34b88
                0x5b34b88: v4i32 = or 0x5b34918, 0x5b34980
                  0x5b34918: v4i32 = and 0x5b33320, 0x5b323e0

                  0x5b34980: v4i32 = and 0x5b31af0, 0x5b33388

            0x5b620e8: v4f32 = fmul 0x5b324e8, 0x5b324e8
              0x5b324e8: v4f32 = bitcast 0x5b32480
                0x5b32480: v4i32 = or 0x5b45a88, 0x5b45af0
                  0x5b45a88: v4i32 = and 0x5b459b8, 0x5b32240

                  0x5b45af0: v4i32 = and 0x5b2f728, 0x5b45a20

              0x5b324e8: v4f32 = bitcast 0x5b32480
                0x5b32480: v4i32 = or 0x5b45a88, 0x5b45af0
                  0x5b45a88: v4i32 = and 0x5b459b8, 0x5b32240

                  0x5b45af0: v4i32 = and 0x5b2f728, 0x5b45a20

          0x5ada138: i32 = Constant<2>
      0x5b06e08: f32 = fsqrt 0x5b06da0
        0x5b06da0: f32 = extract_vector_elt 0x5bb1b90, Constant:i32<3>
          0x5bb1b90: v4f32 = fadd 0x5bb1ac0, 0x5b620e8
            0x5bb1ac0: v4f32 = fmul 0x5b34bf0, 0x5b34bf0
              0x5b34bf0: v4f32 = bitcast 0x5b34b88
                0x5b34b88: v4i32 = or 0x5b34918, 0x5b34980
                  0x5b34918: v4i32 = and 0x5b33320, 0x5b323e0

                  0x5b34980: v4i32 = and 0x5b31af0, 0x5b33388

              0x5b34bf0: v4f32 = bitcast 0x5b34b88
                0x5b34b88: v4i32 = or 0x5b34918, 0x5b34980
                  0x5b34918: v4i32 = and 0x5b33320, 0x5b323e0

                  0x5b34980: v4i32 = and 0x5b31af0, 0x5b33388

            0x5b620e8: v4f32 = fmul 0x5b324e8, 0x5b324e8
              0x5b324e8: v4f32 = bitcast 0x5b32480
                0x5b32480: v4i32 = or 0x5b45a88, 0x5b45af0
                  0x5b45a88: v4i32 = and 0x5b459b8, 0x5b32240

                  0x5b45af0: v4i32 = and 0x5b2f728, 0x5b45a20

              0x5b324e8: v4f32 = bitcast 0x5b32480
                0x5b32480: v4i32 = or 0x5b45a88, 0x5b45af0
                  0x5b45a88: v4i32 = and 0x5b459b8, 0x5b32240

                  0x5b45af0: v4i32 = and 0x5b2f728, 0x5b45a20

          0x5bdbb70: i32 = Constant<3>
    0x5b3a3d8: v4f32 = bitcast 0x5af9a58
      0x5af9a58: v2f64,ch = load<LD16[ConstantPool]> 0x5a5b048, 0x5b3a5e0, undef:i32
        0x5b3a5e0: i32 = ARMISD::Wrapper TargetConstantPool:i32<<4 x float> <float 1.000000e+02, float 1.000000e+02, float 1.000000e+02, float 1.000000e+02>> 0
          0x5bfa648: i32 = TargetConstantPool<<4 x float> <float 1.000000e+02, float 1.000000e+02, float 1.000000e+02, float 1.000000e+02>> 0
        0x5b7a970: i32 = undef
  0x5bfa718: v4f32 = bitcast 0x5ad9778
    0x5ad9778: v2f64,ch = load<LD16[ConstantPool]> 0x5a5b048, 0x5bfa6b0, undef:i32
      0x5bfa6b0: i32 = ARMISD::Wrapper TargetConstantPool:i32<<4 x float> <float 5.000000e+02, float 5.000000e+02, float 5.000000e+02, float 5.000000e+02>> 0
        0x5b7c858: i32 = TargetConstantPool<<4 x float> <float 5.000000e+02, float 5.000000e+02, float 5.000000e+02, float 5.000000e+02>> 0
      0x5b7a970: i32 = undef
In function: Java_com_android_gallery3d_filtershow_filters_ImageFilterEdge_nativeApplyFilter
clang.real: error: clang frontend command failed with exit code 70 (use -v to see invocation)
Android clang version 5.0.300080  (based on LLVM 5.0.300080)
Target: arm--linux-android
Thread model: posix
InstalledDir: prebuilts/clang/host/linux-x86/clang-4053586/bin
clang.real: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang.real: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang.real: note: diagnostic msg: /tmp/edge-b980c3.c
clang.real: note: diagnostic msg: /tmp/edge-b980c3.sh
clang.real: note: diagnostic msg:

This reverts commit 6c6e9c8da8cce5cb9b81dd3309d1647954df67e2.

Change-Id: I08fb2c6ff79aa0928e56f1456a246e14a10db6c3